# Generated by Django 6.0.4 on 2026-05-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_delete_makingof"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tecnologia",
            name="nome",
            field=models.CharField(max_length=150),
        ),
    ]
